name: l10m
description: A library for modular localization in Dart. It allows you to split your localization files into multiple files and load them on demand
version: 1.0.0
repository: https://github.com/augustodia/l10m

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  args: ^2.7.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.26.3
  mocktail: ^1.0.4
  file: ^7.0.1
